export enum ACTIONS {
  SET_USER_SKILLS = "SET_USER_SKILLS",
  SET_USERS_GIT_DETAILS = "SET_USERS_GIT_DETAILS",
  SET_MIN_SALARY_FILTER = "SET_MIN_SALARY_FILTER",
  SET_SKILLS_FILTER = "SET_SKILLS_FILTER",
  SET_USERNAME = "SET_USERNAME",
}
